site_name: Portfolio technique - Jean-Paul Dufour
site_description: Documentation publique de projets techniques
site_author: Jean-Paul Dufour
repo_name: dufourjp/Portfolio
repo_url: https://github.com/dufourjp/Portfolio

theme:
  name: material
  language: fr

nav:
  - Accueil: index.md
  - ESP32 APS ECU:
      - 00) Présentation: esp32-aps-ecu/index.md
      - 01) Pourquoi ce projet ?: esp32-aps-ecu/01-pourquoi-ce-projet.md
      - 02) Architecture générale: esp32-aps-ecu/02-architecture.md
      - 03) Préparation de l'environnement: esp32-aps-ecu/03-preparation-de-l-environnement.md
      - 04) Materiel utilisé: esp32-aps-ecu/04-materiel-utilise.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true